/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AAutoComplete: typeof import('ant-design-vue/es')['AutoComplete']
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACol: typeof import('ant-design-vue/es')['Col']
<<<<<<< HEAD
    ADescriptions: typeof import('ant-design-vue/es')['Descriptions']
    ADescriptionsItem: typeof import('ant-design-vue/es')['DescriptionsItem']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
=======
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AFlex: (typeof import('ant-design-vue/es'))['Flex']
>>>>>>> 067f49cf5a07978c2fcacd1be4adbc99a3ec819f
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AMenu: typeof import('ant-design-vue/es')['Menu']
<<<<<<< HEAD
=======
    AMenuItem: (typeof import('ant-design-vue/es'))['MenuItem']
>>>>>>> 067f49cf5a07978c2fcacd1be4adbc99a3ec819f
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    APopover: typeof import('ant-design-vue/es')['Popover']
    ARadioButton: typeof import('ant-design-vue/es')['RadioButton']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASegmented: typeof import('ant-design-vue/es')['Segmented']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASlider: typeof import('ant-design-vue/es')['Slider']
    AStatistic: typeof import('ant-design-vue/es')['Statistic']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
<<<<<<< HEAD
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    ATypographyParagraph: typeof import('ant-design-vue/es')['TypographyParagraph']
    CloseOutlined: typeof import('@ant-design/icons-vue')['CloseOutlined']
    DeleteOutlined: typeof import('@ant-design/icons-vue')['DeleteOutlined']
=======
    ATag: (typeof import('ant-design-vue/es'))['Tag']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    CloseOutlined: typeof import('@ant-design/icons-vue')['CloseOutlined']
    DeleteOutlined: typeof import('@ant-design/icons-vue')['DeleteOutlined']
    Draggable: typeof import('./components/draggable/Draggable.vue')['default']
>>>>>>> 067f49cf5a07978c2fcacd1be4adbc99a3ec819f
    Icon: typeof import('./components/icon/Icon.vue')['default']
    InfoCircleFilled: typeof import('@ant-design/icons-vue')['InfoCircleFilled']
    LoadingOutlined: typeof import('@ant-design/icons-vue')['LoadingOutlined']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
<<<<<<< HEAD
=======
    TranslationOutlined: (typeof import('@ant-design/icons-vue'))['TranslationOutlined']
>>>>>>> 067f49cf5a07978c2fcacd1be4adbc99a3ec819f
  }
}
